language: python
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
install:
  - pip install pandas
  - pip install biopython
  - pip install httplib2
  - pip install xlrd
  - pip install openpyxl
script:
  - pytest