#!/usr/bin/env python
# coding: utf-8

# Mappings

#List of mcode data elements
valid_mcode = ['date_of_birth',
               'birth_sex',
               'address_zip_code',
               'identifier',
               'race',
               'ethnicity',
               'ecog_performance_status',
               'date_of_diagnosis',
               'history_morphology_behavior',
               'gene_mutation',
               'gene_studied',
               'performing_organization_name',
               'issued',
               'genetic_specimen',
               'genetic_variant',
               'specimen_type',
               'collection_body_site',
               'variant_data_value',
               'tumor_marker_data_value',
               'hemoglobin',
               'hemoglobin_unit',
               'leukocytes_wbc',
               'leukocytes_wbc_unit',
               'platelets',
               'platelets_unit',
               'neutrophils',
               'neutrophils_unit',
               'lymphocytes',
               'lymphocytes_unit',
               'monocytes',
               'monocytes_unit',
               'eosinophils',
               'eosinophils_unit',
               'basophils',
               'basophils_unit',
               'glucose',
               'glucose_unit',
               'sodium',
               'sodium_unit',
               'potassium',
               'potassium_unit',
               'chloride',
               'chloride_unit',
               'serum_creatinine',
               'serum_creatinine_unit',
               'calcium', 'calcium_unit',
               'magnesium',
               'magnesium_unit',
               'ast',
               'ast_unit',
               'bicarbonate',
               'bicarbonate_unit',
               'bun',
               'bun_unit',
               'total_bilirubin',
               'total_bilirubin_unit',
               'total_protein',
               'total_protein_unit',
               'albumin',
               'albumin_unit',
               'phosphate',
               'phosphate_unit',
               'alt',
               'alt_unit',
               'alp',
               'alp_unit',
               'ldh',
               'ldh_unit',
               'medication',
               'body_site',
               'date_of_death',
               'cancer_disease_status_data_value']

#dictionary for mapping of data elements
mcode_dict = {
    'date_of_birth': 'BIRTH_DATE_YM_RAW',
    'birth_sex': 'GENDER_CODE',
    'address_zip_code': 'Site',
    'identifier': 'Subject',
    'race': ['RACE3', 'RACE2', 'RACE10', 'RACE97', 'RACE98', 'RACE99'],
    'ethnicity': 'ETHNICITY_CODE',
    'ecog_performance_status': 'VS_PS',
    'date_of_diagnosis': 'DIAG_PA_RAW',
    'history_morphology_behavior': 'HISTO_CYTO_DIAG',
    'gene_mutation': 'GENE_MUT',
    'gene_studied': 'MUT_TEST',
    'performing_organization_name': 'Site',
    'issued': 'MUT_TEST_DT_RAW',
    'genetic_specimen': 'COLLEC_TIMEPOINT',
    'genetic_variant': 'MUT_STAT',
    'specimen_type': 'BLOOD_TYPE',
    'collection_body_site': 'COLLEC_TIMEPOINT',
    'variant_data_value': 'GENE_MUT',
    'tumor_marker_data_value': 'CEA_VAL',
    'hemoglobin': 'HGB_VAL',
    'hemoglobin_unit': 'HGB_VAL_UN',
    'leukocytes_wbc': 'WBC_VAL_RAW',
    'leukocytes_wbc_unit': 'WBC_VAL_UN',
    'platelets': 'PLT_VAL_RAW',
    'platelets_unit': 'PLT_VAL_UN',
    'neutrophils': 'NEUT_VAL_RAW',
    'neutrophils_unit': 'NEUT_VAL_UN',
    'lymphocytes': 'LYMP_VAL_RAW',
    'lymphocytes_unit': 'LYMP_VAL_UN',
    'monocytes': 'MONO_VAL_RAW',
    'monocytes_unit': 'MONO_VAL_UN',
    'eosinophils': 'EOSI_VAL_RAW',
    'eosinophils_unit': 'EOSI_VAL_UN',
    'basophils': 'BASO_VAL_RAW',
    'basophils_unit': 'BASO_VAL_UN',
    'glucose': 'GLUC_VAL_RAW',
    'glucose_unit': 'GLUC_VAL_UN',
    'sodium': 'NA_VAL_RAW',
    'sodium_unit': 'NA_VAL_UN',
    'potassium': 'K_VAL_RAW',
    'potassium_unit': 'K_VAL_UN',
    'chloride': 'CL_VAL_RAW',
    'chloride_unit': 'CL_VAL_UN',
    'serum_creatinine': 'S_CREAT_VAL_RAW',
    'serum_creatinine_unit': 'S_CREAT_VAL_UN',
    'calcium': 'CA_VAL_RAW',
    'calcium_unit': 'CA_VAL_UN',
    'magnesium': 'MG_VAL_RAW',
    'magnesium_unit': 'MG_VAL_UN',
    'ast': 'AST_VAL_RAW',
    'ast_unit': 'AST_VAL_UN',
    'bicarbonate': 'BICARB_VAL_RAW',
    'bicarbonate_unit': 'BICARB_VAL_UN',
    'bun': 'BUN_VAL_RAW',
    'bun_unit': 'BUN_VAL_UN',
    'total_bilirubin': 'T_BILI_VAL_RAW',
    'total_bilirubin_unit': 'T_BILI_VAL_UN',
    'total_protein': 'TPROT_VAL_RAW',
    'total_protein_unit': 'TPROT_VAL_UN',
    'albumin': 'ALB_VAL_RAW',
    'albumin_unit': 'ALB_VAL_UN',
    'phosphate': 'PHOS_VAL_RAW',
    'phosphate_unit': 'PHOS_VAL_UN',
    'alt': 'ALT_VAL_RAW',
    'alt_unit': 'ALT_VAL_UN',
    'alp': 'ALKPHOS_VAL_RAW',
    'alp_unit': 'ALKPHOS_VAL_UN',
    'ldh': 'LDH_VAL_RAW',
    'ldh_unit': 'LDH_VAL_UN',
    'weight_before_illness': 'WEIGHT_BEFORE_STD',
    'weight_before_illness_unit': 'WEIGHT_BEFORE_STD_UN',
    'weight_around_25': 'WEIGHT_25_AGE_STD',
    'weight_around_25_unit': 'WEIGHT_25_AGE_STD_UN',
    'height': 'HEIGHT_STD',
    'height_unit': 'HEIGHT_STD_UN',
    'medication': 'THER_TX_NAME',
    'body_site': 'RADIOLOGY_TEST_SITE',
    'date_of_death': 'DTH_DT_RAW',
    'cancer_disease_status_data_value': 'DISEASE_STATUS'
}

#extra_properties in tumor_marker field
lab_results = ['hemoglobin', 'hemoglobin_unit', 'leukocytes_wbc', 'leukocytes_wbc_unit', 'platelets', 'platelets_unit',
               'neutrophils', 'neutrophils_unit', 'lymphocytes', 'lymphocytes_unit', 'monocytes', 'monocytes_unit', 'eosinophils',
               'eosinophils_unit', 'basophils', 'basophils_unit', 'glucose', 'glucose_unit', 'sodium', 'sodium_unit', 'potassium',
               'potassium_unit', 'chloride', 'chloride_unit', 'serum_creatinine', 'serum_creatinine_unit', 'calcium', 'calcium_unit',
               'magnesium', 'magnesium_unit', 'ast', 'ast_unit', 'bicarbonate', 'bicarbonate_unit', 'bun', 'bun_unit', 'total_bilirubin',
               'total_bilirubin_unit', 'total_protein', 'total_protein_unit', 'albumin', 'albumin_unit', 'phosphate', 'phosphate_unit',
               'alt', 'alt_unit', 'alp', 'alp_unit', 'ldh', 'ldh_unit']

#extra_properties in subject field
vital_signs = ['weight_before_illness', 'weight_before_illness_unit',
               'weight_around_25', 'weight_around_25_unit', 'height']

#map race codes to race
race_mapping_dict = {
    'RACE3': 'white',
    'RACE2': 'white',
    'RACE10': 'black or african american',
    'RACE97': 'american indian or alaska native',
    'RACE98': 'asian',
    'RACE99': 'native hawaiian or pacific islander'
}

#list of data elements in array form in mcode
possible_multi_val = ['gene_mutation', 'gene_studied', 'genetic_specimen',
                      'medication', 'tumor_marker_data_value', 'collection_body_site', 'body_site']
