name: Github Actions Test

on: [push]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install -U pip
          pip install -U pytest
          pip install pandas
          pip install biopython
          pip install httplib2
          pip install xlrd
          pip install openpyxl
      - name: Test with pytest
        run: |
          pytest
